import type { Metadata } from "next";
import { inter, spaceGrotesk } from "./fonts";
import "./globals.css";
import { ModeProvider } from "@/context/ModeContext";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${spaceGrotesk.variable}`}>
      <body className="font-sans bg-background text-copy antialiased">
        <ModeProvider>
          <Navbar />
          <main>{children}</main>
        </ModeProvider>
      </body>
    </html>
  );
}
